# Configura el contenedor de la base de datos para que utilice
# un directorio del anfitrión como almacén de la base de datos.
# El nombre del directorio *completo* se debe recibir en la
# variable de entorno $HOST_DB_PATH
# Ese directorio *debe tener dentro* un subdirectorio data y otro
# logs, ambos escribibles por el usuario UID/GUID.

version: '3.3'
  
services:
    db:
        user: ${UID:-1000}:${GUID:-1000}
        volumes:     
            - ${HOST_DB_PATH}/data:/var/lib/mysql
            - ${HOST_DB_PATH}/logs:/var/log/mysql
